projects:

  cluster-config:
    annotations:
      notifications.argoproj.io/subscribe.on-sync-failed.slack: cluster-gitops
      notifications.argoproj.io/subscribe.on-health-degraded.slack: cluster-gitops
    description: Project for overall cluster configuration
    namespace: openshift-gitops
    sourceRepos:
    - ${INFRA_GITOPS_REPO}
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications: 

# Basic

  web-terminal-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '20'
    source:
      path: components/web-terminal-operator 

# Storage


# Observability

  kube-ops-view:
    annotations:
      argocd.argoproj.io/sync-wave: '20'
    destination:
      namespace: kube-ops-view
    source:
      path: components/kube-ops-view       

# Networking

  cert-manager-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '20'
    source:
      path: components/cert-manager-operator

  cert-manager-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: cert-manager
    source:
      path: components/cert-manager-configuration

  external-dns-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '20'
    source:
      path: components/external-dns-operator

  external-dns-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: external-dns
    source:
      path: components/external-dns-configuration      

  metallb-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '20'
    source:
      path: components/metallb-operator

  nmstate-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '20'
    source:
      path: components/nmstate-operator 

  nmstate-instance:
    annotations:
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: openshift-nmstate
    source:
      path: components/nmstate-instance

              