apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: etl4-master-1
  namespace: etl4
  labels:
    infraenvs.agent-install.openshift.io: etl4
spec:
  config:
    interfaces:
    - name: enp1s0
      type: ethernet
      state: up
      ipv4:
        enabled: true
        address:
          - ip: 192.168.139.161
            prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        server:
        - 192.168.139.1
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.139.1
        next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: 52:54:00:aa:04:01
