apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: etl4-master-2
  namespace: etl4
  labels:
    infraenvs.agent-install.openshift.io: etl4
spec:
  config:
    interfaces:
    - name: eth0
      type: ethernet
      state: up
      ipv4:
        enabled: true
        address:
          - ip: 192.168.123.222
            prefix-length: 24
        dhcp: false
  interfaces:
    - name: eth0
      macAddress: 52:54:00:aa:04:02
