apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./spoke1-master-0-baremetal-host.yaml
  - ./spoke1-master-1-baremetal-host.yaml
  - ./spoke1-master-2-baremetal-host.yaml
  - ./spoke1-master-0-nmstate-config.yaml
  - ./spoke1-master-1-nmstate-config.yaml
  - ./spoke1-master-2-nmstate-config.yaml
  - ./spoke1-master-0-fqdn.yaml
  - ./spoke1-master-1-fqdn.yaml
  - ./spoke1-master-2-fqdn.yaml

helmGlobals:
  chartHome: ../../../../.helm-charts

helmCharts:
  - name: bm-cluster-agent-install
    releaseName: spoke1
    namespace: spoke1
    valuesInline:
      clusterSet: default
      location: cert-lab
      workerNumber: 0
      imageSet: img4.18.12-x86-64-appsub
      mastersSchedulable: true
      sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWVnOEYFaN6tp/CXn5aBgD5YZbbwJHhUYbAahoGz3IbP8YZZwyBvJvgy9CujKTaIpZHweYRwMEtvPaX65g8AQDd8t6Gqc+JVJue6HTqrawH2wvq8Qdhip9L09fK2WqtP7UbVF+fgiwm9kebajkAqtlOttcdHipeRy5TGVE2hbV1zqc6UjTo6lKzxflm2Jd5EMc4TZCleSFApBod+jgFZoke/8Q/GHWyQs7YaoE3h/JND7z6aye5HoAPQBT18y/4Amwj7h2hIcIsSJ8JAHsOZ0NB4gz1qwpkG/dYAYV1iARM/+qnZ7EJAt4DofqUAS1/0BdXK+1RL8uI0db4r8U3pTe+oFGORQHRNa+ehDoX1PdOU+o59OmjEaJpcq0YRB3NqOwfZzATUfOqcZswH0xC6WKi/UknBFPgJv6JfD0+dee/kWTmgFrzT6Ie9hRql2bA+qjSoPfWzPk+Gv1Wuf6UGdC2DpKPO+vOhVzRtog/cvwjGSJv5p2X6biRGiYy8a0bX0= rspazzol@rspazzol
      networking:
        podCIDR: 10.132.0.0/14
        serviceCIDR: 172.31.0.0/16
        ingressVIP: "192.168.123.200"
        apiVIP: "192.168.123.201"
  - name: cluster-registration
    releaseName: spoke1
    namespace: spoke1
    valuesInline:
      clusterSet: default
