location: mylab
workerNumber: 0
imageSet: none
clusterSet: default
sshKey: none
baseDomain: qe.lab.redhat.com
mastersSchedulable: false
networking:
  podCIDR: 0.0.0.0/0
  serviceCIDR: 0.0.0.0/0
  hostPrefix: 24
  ingressVIP: "0.0.0.0"
  apiVIP: "0.0.0.0"
