apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: etl6-master-0
  namespace: etl6
  labels:
    infraenvs.agent-install.openshift.io: etl6
spec:
  config:
    interfaces:
    - name: enp1s0
      type: ethernet
      state: up
      ipv4:
        enabled: true
        address:
          - ip: 192.168.135.170
            prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        server:
        - 192.168.135.1
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.135.1
        next-hop-interface: enp1s0
  interfaces:
    - name: enp1s0
      macAddress: 52:54:00:aa:06:00
